"""Update resource quantity defaults

Revision ID: 8612423824e0
Revises: 8fa19c8ee2cf
Create Date: 2024-06-02 19:13:08.257206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8612423824e0'
down_revision = '8fa19c8ee2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_needed', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_available', sa.Integer(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity_available')

    with op.batch_alter_table('project_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity_needed')

    # ### end Alembic commands ###
